version: "3.8"

# virtual networks inside cluster, to let runing containers talk to each other
networks:
  nginx-reverse: # root nginx-reverse to api-example and wp

# declare all services: nginx-reverse (api-example (redis, mongo), wp (mysql))
services:
  # root service: nginx as reverse-proxy for 1) api-example and 2) wp
  nginx-reverse:
    image: nginx
    restart: always
    deploy:
      placement: # to run this service on a specific node
        constraints:
          - 'node.role == manager'
    ports: # exposed ports out of cluster
      - 3000:80
      # - 443:443 # if you have certs
    networks:
      - nginx-reverse
    depends_on: # do not start service until dependencies are started
      - risevest
    volumes:
      - ./nginx-reverse/default.conf:/etc/nginx/conf.d/default.conf  

  # 1) api-example + redis + mongo
  risevest:
    image: risevest-ms # specify your repo name
    build: # to build image with docker-compose
      context: ../../
      # dockerfile: /var/www/html/transcode-ms/Dockerfile
    restart: always
    # deploy: # uncomment to run multiple api-example services
    #   replicas: 4
    #   resources:
    #     limits:
    #       cpus: "1.5"
    #       memory: 256M

    env_file:
      - .env
    # environment:
        # - ENVIRONMENT=production
        # - NODE_ENV="dev"
        # - DATABASE_HOST=dpg-cjlo05ocfp5c73aa64d0-a
        # - DATABASE_PORT=5432
        # - DATABASE_USER=risevest
        # - DATABASE_PASSWORD=gPRhk5FTcnYOrTSLK6TLMY7evBuwBjhU
        # - DATABASE_NAME=risevest_myk7
        # - JWT_SECRET='MIICXAIBAAKBgQCGhLlpouwodWJ7O+ErKGXSGw18oKN7OKgaxxa878PWRAdKGxDCLape3t/MS12R8kq98qppBqaTq9whX1k/cYIPsBqbLFib1ZXwlJ2635lp+X1h2ij8w1IMYkCtkpcaS9J1NWyRp2YGRFIb4fSu1DLVeBEt+JoQhUikQmmbYEgrqQIDAQABAoGAA9BLeWU3EMaTLi86aQDSMiy2KyxatimbCndOe7jIcpCnLECsLvUgeWQUMDSKyJJ37/6rOiMIIfOjYAbV/uh26XReoxgrrd+keiohSAmoS8J+gTZbPyniLbnpc/emBfdiF2etJ6G5RD4bAWSnYZMFR3zLTv0w+bUhK5W3bYuyHSECQQDNvjAMT9JSRB3es0zsDFjtqY2ogDNkEzhOPJc7+cT9K9LSEZpdq9HrDGih714Y/NlkM8Lublfsxz2OqJh3173NAkEAp2CgMqqJrOGx1a6b12W9t3fUoF+Nay9zV6R7mDNLMW7ckHiL+NzuKoehHBcyFpS1hdbVnVPUadBj0wdh0rdpTQJACAiYGbL4NGwienKn20O0KTuIo362Av9ZIHzvLtFW5sfSSI+VZnjyDmqCn2gYVYNx/Z6jyumWF1HETpC4u106NQJBAJfPAt2RYdekyLfna7+crsrl67sdj1WlLvdR3yu3cj6+r1x1iXbJY1a9tzmULEDg1hczOII+k0z5zmCLtIT7B40CQFRsWGw6bw2z+QHfdLTClV3OQndvPMV4VAdnJFxBqcAA2ZRCLbcV9QV/YsXf/k0xT0l8tuWgfR0RSKR8WTSikzU='

    # ports: # exposed ports out of cluster
    #   - 3000:3000  
    networks:
      - nginx-reverse


